---
- hosts: localhost
  become: true
  gather_facts: true
  gather_subset:
    - '!all'
  tasks:
    - name: Packages CentOS/RHEL
      package:
        name:
          - epel-release
          - /usr/bin/pip
          - bind-utils
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Packages Ubuntu
      package:
        name:
          - python-pip
          - python3-pip
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Packages
      package:
        name:
          - git
          - vim
          - pwgen
          - tmux
          - rsync
          - bash-completion
          - ack
          - python
          - wget
          - curl
        state: present

    - name: install pip resources
      pip:
        name: ansible-lint
