---
- hosts: localhost
  become: true
  tasks:
    - name: Packages CentOS/RHEL
      package:
        name:
          - epel-release
          - python2-pip
          - bind-utils
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Packages Ubuntu
      package:
        name:
          - python-pip
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Packages
      package:
        name:
          - git
          - vim
          - pwgen
          - tmux
          - rsync
          - bash-completion
          - ack
          - python
          - wget
          - curl
        state: present

    - name: install pip resources
      pip:
        name: ansible-lint

# USER stuff
- hosts: localhost
  vars_prompt:
    - name: gitemail
      prompt: 'What is your git email?'
      default: 'wouter@schoot.org'
      private: no

    - name: gitname
      prompt: 'What is your git name?'
      default: 'Wouter Schoot'
      private: no

  become: false
  tasks:
    - name: mkdir .dotfiles
      file:
        path: ~/.dotfiles
        state: directory

    - name: gitprompt.sh
      copy:
        src: files/git-prompt.sh
        dest: ~/.git-prompt.sh

    - name: gitconfig
      template:
        src: templates/gitconfig.j2
        dest: ~/.dotfiles/gitconfig

    - name: symlink gitconfig
      file:
        src: ~/.dotfiles/gitconfig
        dest: ~/.gitconfig
        state: link
        force: yes

    - name: vimrc
      template:
        src: templates/vimrc.j2
        dest: ~/.dotfiles/vimrc

    - name: symlink vimrc
      file:
        src: ~/.dotfiles/vimrc
        dest: ~/.vimrc
        state: link
        force: yes

    - name: tmux
      template:
        src: templates/tmux.conf.j2
        dest: ~/.dotfiles/tmux.conf

    - name: symlink tmux
      file:
        src: ~/.dotfiles/tmux.conf
        dest: ~/.tmux.conf
        state: link
        force: yes

    - name: bash_profile
      template:
        src: templates/bash_profile.j2
        dest: ~/.dotfiles/bash_profile

    - name: symlink bash_profile
      file:
        src: ~/.dotfiles/bash_profile
        dest: ~/.bash_profile
        state: link
        force: yes

    - name: run vim -r to prep the env
      command: vim -r
      args:
        creates: ~/.vim
